name: cmark_gfm_widget_example
description: Example application for cmark_gfm_widget.
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cmark_gfm_widget:
    path: ..
  pixel_snap: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
